config/routes.rb
DiplomacyTurns::Application.routes.draw do
  resources :turns

  get  "/admin"       => "admin#index",       :as => "admin"
  post "/start_game"  => "admin#start_game",  :as => "start_game"
  get  "/config_game" => "admin#config_game", :as => "config_game"
  get  "/next_round"  => "admin#next_round",  :as => "next_round"
  get  "/defeat"      => "admin#defeat",      :as => "defeat"

  get "/current_round" => "round#index",      :as => "current_round"
  devise_for :users
  get "/home" => "user#home"
  root :to => "turns#index"
end

app/models/turn.rb
class Turn < ActiveRecord::Base
  attr_accessible :orders, :user, :round, :active, :user_id
  belongs_to :user


  scope :active,   where(:active => true)
  scope :inactive, where(:active => false)

  def self.current_inactive_round
    if Turn.all.count == 0
      0
    else
      self.inactive.order("round DESC").first.round
    end
  end
  def self.current_active_round
    if Turn.all.count == 0
      1
    elsif Turn.active.empty? 
      self.current_inactive_round + 1
    else
      Turn.active.first.round
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  NATIONS = %w{ France Italy Germany Russia Turkey Austria Britain }

  scope :alive,   where(:alive => true)
  scope :players, where("nation IS NOT null")
  
  # Allow nil because new users won't have a nation
  # until a game is started
  validates :nation, :inclusion  => { :in => NATIONS, :allow_nil => true }
  validate do |user|
    return true if user.nation.nil?
    users = User.where(:nation => user.nation)
    unless users.length == 0 || (users.length == 1 && users[0] == user)
      errors.add(:base, "Only one player per nation")
    end
  end

  has_many :turns
  
  def active_turn
    self.turns.active
  end
  # attr_accessible :title, :body
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :initialize_shamewall, :only => [:index]

  def index; end

  def next_round
    Turn.active.each do |turn|
      turn.active = false
      turn.save
    end

    initialize_turns

    flash[:notice] = "THE GAME HAS PROGRESSED"
    redirect_to current_round_path
  end


  def config_game
    @users = User.all # if this is more than 7 people yer doin' it wrong
  end

  def start_game
    Turn.destroy_all
    initialize_turns
    initialize_nations
    flash[:notice] = "A NEW GAME HAS BEEN STARTED"
    redirect_to turns_path
  end

  def defeat
    user = User.find(params[:user_id])
    user.alive = false
    user.save!
    redirect_to admin_path
  end

private
  def initialize_nations
    User.all.each do |user|
      user.nation = nil
      user.alive  = false
      user.save!
    end
    User::NATIONS.each do |nation|
      next if params[nation].blank?
      user = User.find(params[nation])
      user.nation = nation
      user.alive  = true
      user.save!
    end
  end

  def initialize_turns
    User.all.each do |user|
      Turn.create(:user => user, :round => Turn.current_active_round)
    end
  end
  def initialize_shamewall
    @shame_wall = User.players.map do |p|
      binding.pry
      if !p.alive
        [p, :dead]
      elsif p.active_turn.first.orders.blank?
        [p, :shame]
      else
        [p, :noshame]
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery
end

app/controllers/round_controller.rb
class RoundController < ApplicationController
  def index
    current_round = Turn.current_inactive_round
    @turns = Turn.where(:round => current_round)
  end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  # GET /turns
  # GET /turns.json
  def index
    @inactive_turns = Turn.inactive.where(:user_id => current_user.id).order("round DESC")
    @turn = Turn.where(:user_id => current_user.id).active.first.presence || Turn.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @turns }
    end
  end

  # GET /turns/1
  # GET /turns/1.json
  def show
    @turn = Turn.find(params[:id])
    redirect_to turns_path if @turn.active && @turn.user.id != current_user.id


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @turn }
    end
  end

  # POST /turns
  # POST /turns.json
  def create
    @turn = Turn.new(params[:turn])

    @turn.user = current_user

    respond_to do |format|
      if @turn.save
        format.html { redirect_to turns_path, notice: 'Turn was successfully created.' }
        format.json { render json: @turn, status: :created, location: @turn }
      else
        format.html { render action: "new" }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /turns/1
  # PUT /turns/1.json
  def update
    @turn = Turn.find(params[:id])

    respond_to do |format|
      if @turn.update_attributes(params[:turn])
        format.html { redirect_to turns_path, notice: 'Turn was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/config_game.html.haml
%h1 Setup New Game

= form_tag(start_game_path) do
  - User::NATIONS.each do |nation|
    %h3= nation
    = select_tag nation, options_from_collection_for_select(@users, "id", "email"), :include_blank => true
    %br

  = submit_tag "Start New Game", :confirm => "This will destroy all existing game data and start a new game"

app/views/admin/index.html.haml
- shame   = "HAS NOT YET PLACED ORDERS"
- noshame = "has placed orders"
- dead    = "has been defeated"
%h1 ADMIN PANEL

%h3 Has everyone gone?

%ul 
  - @shame_wall.each do |msg|
    %span{:style => "text-decoration: underline"}= msg[0].nation
    - if msg[1] == :shame
      %strong= shame
    - elsif msg[1] == :noshame
      %span= noshame
    - else
      %span= dead

    - if msg[0].alive
      \---------
      = link_to " Defeated?", {:controller => "admin", :action => "defeat", :user_id => msg[0].id}


    %br



= link_to "Reset game", config_game_path

= link_to "Progress game", next_round_path, :data => { :confirm => 'Are you sure?' }

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title='DiplomacyTurns'
    = stylesheet_link_tag "bootstrap","application", :media => "all"
    = javascript_include_tag "jquery", "bootstrap", "sketch", "application"
    = csrf_meta_tags
  %body
    .title_container
      = image_tag('/assets/diplomacy_small.png')
    .container
      %p.notice= notice
      - if alert
        %p.alert= alert
      .buttons_right
        = link_to "Log out", destroy_user_session_path, :method => :delete
      = yield

app/views/round/index.html.haml
%h1== Round #{Turn.current_inactive_round}


%table
  %tr
    %th User
  - @turns.each do |turn|
    %tr
      - if turn.user.alive
        %td= link_to turn.user.nation, turn
      - else
        %td.dead= turn.user.nation

app/views/turns/_form.html.haml
= form_for @turn do |f|
  - if @turn.errors.any?
    #error_explanation
      %h2= "#{pluralize(@turn.errors.count, "error")} prohibited this turn from being saved:"
      %ul
        - @turn.errors.full_messages.each do |msg|
          %li= msg

  .turn
    = f.label     :orders
    = f.text_area :orders

  .actions
    = f.submit 'Save'

app/views/turns/edit.html.haml
%h1 Editing turn

= render 'form'

= link_to 'Show', @turn
\|
= link_to 'Back', turns_path

app/views/turns/index.html.haml
%h1== Current Turn: Round #{Turn.current_active_round}
%h2== Orders for #{@turn.user.nation}

= render "form"

%h3 Previous turns

%table
  %tr
    %th

  - @inactive_turns.each do |turn|
    %tr
      %td= link_to "Round #{ turn.round}", turn

%br

app/views/turns/new.html.haml
%h1 New turn

= render 'form'

= link_to 'Back', turns_path

app/views/turns/show.html.haml
%h1== Orders for #{@turn.user.nation}
- orders = @turn.orders
%p#notice= notice

.orders
  - if orders
    - @turn.orders.split("\n").each do |order|
      %p= order
  - else
    %p== #{@turn.user.email} did not submit orders.
    %p Their government has fallen in civil war.
    %p All of their nation's units will hold their ground.
    %p Any units forced to retreat will be disbanded.
      

- if @turn.active
  = link_to 'Edit', edit_turn_path(@turn)
  \|
= link_to 'Back', turns_path

app/views/user/home.html.haml
.map_tools
  =link_to "Pen", "#current_board", {'data-tool' => "marker", 'data-size' => '5'}
  =link_to "Eraser", "#current_board", {'data-tool' => "eraser", 'data-size' => '15'}
  %canvas#current_board{:width => '1000px', :height => '838px', :style => 'background: url(/assets/map.gif) no-repeat center center;'}
  =link_to "Take Snapshot", "#current_board", {'data-download' => 'png'}